# Generated by Django 5.2.7 on 2025-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_outbid',
            field=models.BooleanField(default=False),
        ),
    ]
