# Generated by Django 5.2.7 on 2025-12-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_bid_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='display_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lot',
            name='display_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
