# Generated by Django 5.2.7 on 2025-12-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_lot_display_first_name_lot_display_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBids',
        ),
    ]
