# Generated by Django 5.2.7 on 2025-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [ migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
