# Generated by Django 5.2.7 on 2025-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_add_is_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, null=True, blank=True, unique=True),
        ),
    ]